# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "syncywinky"
mod.name = "Syncy Winky"
mod.group = "z3roco01.syncywinky"
mod.version = "1.3.0"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["1.18.2"]
mod.mc_releases = ["1.18", "1.18.1", "1.18.2"]

[fabric."1.18.2"]
mod.mc_compat = ">=1.18 <=1.18.2"
deps.fabric_api = "0.77.0+1.18.2"

["1.19.2"]
mod.mc_releases = ["1.19", "1.19.1", "1.19.2"]

[fabric."1.19.2"]
mod.mc_compat = ">=1.19 <=1.19.2"
deps.fabric_api = "0.77.0+1.19.2"

["1.20.1"]
mod.mc_releases = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.20.5", "1.20.6"]

[fabric."1.20.1"]
mod.mc_compat = ">=1.20 <=1.20.6"
deps.fabric_api = "0.92.12+1.20.1"

[forge."1.20.1"]
mod.mc_compat = "[1.20, 1.20.6]"
deps.forge = "1.20.1-47.4.10"
deps.minecraft = "1.20.1"

["1.21.1"]
# List of releases to be marked compatible on Modrinth/Curseforge
mod.mc_releases = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10", "1.21.11"]

[fabric."1.21.1"]
# Mod compatibility range in fabric.mod.json/neoforge.mods.toml
mod.mc_compat = ">=1.21 <=1.21.11"
deps.fabric_api = "0.116.15+1.21.1"


[neoforge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.11]"
deps.neo_loader = "21.1.248"

["26.1"]
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]


[fabric."26.1"]
mod.mc_compat = ">=26.1 <26.2"
deps.fabric_api = "0.145.1+26.1"


[neoforge."26.1"]
mod.mc_compat = "[26.1, 26.1.2]"
deps.neo_loader = "26.1.2.109"

["26.2"]
mod.mc_releases = ["26.2"]

[fabric."26.2"]
mod.mc_compat = "~26.2"
deps.fabric_api = "0.160.0+26.2"


[neoforge."26.2"]
mod.mc_compat = "[26.2, 26.3)"
deps.neo_loader = "26.2.0.85"
