license = "GPL-v3"

modLoader="javafml"
loaderVersion="[1,)"
clientSideOnly=true

[[mods]]
modId = "syncywinky"
displayName = "Syncy Winky"
version = "${version}"
authors = "z3roco01"
description = "Syncs your game settings across all instacnes !"

logoFile = "assets/syncywinky/icon.png"
iconFile = "assets/syncywinky/icon.png"
#displayURL = "..."
#issueTrackerUrl = "..."

[[mixins]]
config = "syncywinky.mixins.json"

[[dependencies.syncywinky]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"