license = "GPL-v3"

modLoader="javafml"
loaderVersion="[1,)"
clientSideOnly = true

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "z3roco01"
description = "Syncs your game settings across all instacnes !"

logoFile = "assets/syncywinky/icon.png"
iconFile = "assets/syncywinky/icon.png"
#displayURL = "..."
#issueTrackerUrl = "..."

[[mixins]]
config = "syncywinky.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.neoforge.cfg"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"